<a href="https://colab.research.google.com/github/ashaaher/Emerging-Technologies/blob/master/Assignment_1_Part_2/iris_Semi_Supervided.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
pip install pypcc

In [51]:
pip install sklearn

In [52]:
from sklearn import datasets
iris_data = datasets.load_iris
data_value = iris.data
label = iris.target

In [58]:
import numpy as np
import random


def maskData(true_labels, percentage):

  mask = np.ones((1,len(true_labels)), dtype=bool)[0]
  labels = true_labels.copy()

  for l,enc in zip(np.unique(true_labels), range(0,len(np.unique(true_labels)))):

    deck = np.argwhere(true_labels == 1).flatten()
    random.shuffle(deck)

    mask[deck[:int(percentage * len(true_labels[true_labels == 1]))]] = False

    labels[labels == 1] =enc
  labels[mask] = -1

  return np.array(labels).astype(int)

In [61]:

import numpy as np
from sklearn import datasets
from sklearn.metrics import confusion_matrix
from sklearn.semi_supervised import LabelPropagation

def runLP():

  # database importing
  iris = datasets.load_iris()
  data = iris.data
  labels = iris.target

  #unlabeling 95% of the dataset 
  masked_labels = maskData(labels, 0.05)

  #running the model
  model = LabelPropagation()
  model.fit(data,masked_labels)
  pred = np.array(model.predict(data))

  #seperating predicted samples
  labels = np.array(labels[masked_labels == -1]).astype(int)
  pred = pred[masked_labels == -1]

  #printing confusion matrix
  print(confusion_matrix(labels,pred))

if __name__ == '__main__':
  runLP()

[[50  0  0]
 [45  0  0]
 [50  0  0]]
